# Generated by Django 4.1.5 on 2023-01-07 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailuser',
            name='password',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='emailuser',
            name='re_type_password',
            field=models.CharField(max_length=100),
        ),
    ]
