# Generated by Django 4.1.5 on 2023-01-12 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_otp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Otp',
        ),
        migrations.AddField(
            model_name='emailuser',
            name='otp',
            field=models.IntegerField(default=0),
        ),
    ]
