# Generated by Django 4.1.5 on 2023-01-13 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_delete_otp_emailuser_otp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Otp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=13)),
                ('otp', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='emailuser',
            name='otp',
        ),
        migrations.AlterField(
            model_name='emailuser',
            name='phone_number',
            field=models.CharField(max_length=13, null=True),
        ),
    ]
