# Generated by Django 4.1.4 on 2023-03-31 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_otp_remove_emailuser_otp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailuser',
            name='blocked',
            field=models.BooleanField(default=False),
        ),
    ]
