# Generated by Django 4.1.5 on 2023-01-09 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_rename_item_image_product_productimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='productimage',
            new_name='image',
        ),
    ]
