# Generated by Django 4.1.5 on 2023-01-09 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_rename_productimage_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='image',
            new_name='product_image',
        ),
    ]
