# Generated by Django 4.1.3 on 2023-03-21 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0016_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='status',
        ),
        migrations.RemoveField(
            model_name='product',
            name='status',
        ),
    ]
