# Generated by Django 4.1.5 on 2023-04-06 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0027_alter_product_name_alter_product_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='coupon_discount',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='cart',
            name='discount',
            field=models.IntegerField(null=True),
        ),
    ]
