# Generated by Django 4.1.5 on 2023-04-06 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0028_cart_coupon_discount_cart_discount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='coupon_discount',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='discount',
        ),
    ]
